print("Hola, conoce u índice de masa corporal")
peso = float(input("Introduce tu peso en kilogramos: "))
altura = float(input("Introduce tu altura en metros: "))
imc = peso / (altura ** 2)
print(f"Tu índice de masa corporal es: {imc:.2f} kg/m²")